apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
        - name: ansible
          image: ansible-in-pod
          command: ["sleep"]
          args: ["infinity"]
          securityContext:
            runAsUser: 0